apps/sspanel/urls.py
from django.urls import path
from .import views


app_name = "sspanel"
urlpatterns = [
    # 网站用户面板
    path('sshelp/', views.sshelp, name='sshelp'),
    path('ssclient/', views.ssclient, name='ssclient'),
    path('ssinvite/', views.ssinvite, name='ssinvite'),
    path('passinvite/(<invitecode>)/',
         views.pass_invitecode, name='passinvitecode'),
    # 注册/登录
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    # 节点
    path('nodeinfo/', views.nodeinfo, name='nodeinfo'),
    path('trafficlog/', views.trafficlog, name='trafficlog'),
    # 用户信息
    path('users/userinfo/', views.userinfo, name='userinfo'),
    path('users/userinfoedit/', views.userinfo_edit, name='userinfo_edit'),
    #  二维码
    path('qrcode/ssr/<node_id>/',
         views.get_ssr_qrcode, name='ssrqrcode'),
    path('qrcode/ss/<node_id>/',
         views.get_ss_qrcode, name='ssqrcode'),
    # 捐赠/充值
    path('donate/', views.donate, name='donate'),
    path('shop/', views.shop, name='shop'),
    path('purchaselog/', views.purchaselog, name='purchaselog'),
    path('chargecenter/', views.chargecenter, name='chargecenter'),
    path('charge/', views.charge, name='charge'),
    # 公告
    path('announcement/', views.announcement, name='announcement'),
    # 工单
    path('ticket/', views.ticket, name='ticket'),
    path('ticket/create/', views.ticket_create, name='ticket_create'),
    path('ticket/edit/(<int:pk>)/',
         views.ticket_edit, name='ticket_edit'),
    path('ticket/delete/<int:pk>)/',
         views.ticket_delete, name='ticket_delete'),
    # 推广相关
    path('affiliate/', views.affiliate, name='affiliate'),
    path('rebate/record/', views.rebate_record, name='rebate'),
    # 网站后台面板
    path('backend/', views.backend_index, name='backend_index'),
    # 邀请码相关
    path('backend/invite/', views.backend_invite, name='backend_invite'),
    path('invite_gen_code/', views.gen_invite_code, name='geninvitecode'),
    # 节点相关
    path('backend/nodeinfo/', views.backend_node_info,
         name='backend_node_info'),
    path('backend/node/delete/<int:node_id>/',
         views.node_delete, name='node_delete'),
    path('backend/node/edit/<int:node_id>/',
         views.node_edit, name='node_edit'),
    path('backend/node/create/', views.node_create, name='node_create'),
    # 用户相关
    path('backend/userlist/', views.backend_userlist, name='user_list'),
    path('backend/user/delete/<int:pk>/',
         views.user_delete, name='user_delete'),
    path('backend/user/search/', views.user_search, name='user_search'),
    path('backend/user/status/', views.user_status, name='user_status'),
    # 商品充值相关
    path('backend/charge/', views.backend_charge, name='backend_charge'),
    path('backend/shop/', views.backend_shop, name='backend_shop'),
    path('backend/shop/delete/<int:pk>/',
         views.good_delete, name='good_delete'),
    path('backend/good/create/', views.good_create, name='good_create'),
    path('backend/good/edit/<int:pk>/',
         views.good_edit, name='good_edit'),
    path('backend/purchase/history/',
         views.purchase_history, name='purchase_history'),
    # 支付宝当面付相关:
    path('facepay/qrcode/', views.gen_face_pay_qrcode, name='facepay_qrcode'),
    # 公告管理相关
    path('backend/anno/', views.backend_anno, name='backend_anno'),
    path('backend/anno/delete/<int:pk>/',
         views.anno_delete, name='anno_delete'),
    path('backend/anno/create/', views.anno_create, name='anno_create'),
    path('backend/anno/edit/<int:pk>/',
         views.anno_edit, name='anno_edit'),
    # 工单相关
    path('backend/ticket/', views.backend_ticket, name='backend_ticket'),
    path('backend/ticket/edit/<int:pk>/',
         views.backend_ticketedit, name='backend_ticketedit'),
    # 在线ip
    path('backend/aliveuser/', views.backend_alive_user, name='alive_user'),

]

apps/urls.py
from django.urls import path, include
from django.contrib import admin

from apps.sspanel.views import index

urlpatterns = [
    path('', index, name="index"),
    path('', include('django.contrib.auth.urls')),
    path('api/', include('apps.api.urls', namespace='api')),
    path('sspanel/', include('apps.sspanel.urls', namespace='sspanel')),
    path('server/', include('apps.ssserver.urls', namespace='ssserver')),

    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', 'jet'))
]

templates/backendbase.html
{% load ehcofilter %}
<!DOCTYPE html>
<html lang="zh">

<head>
    {% load staticfiles %}
    <title>{% settings_value "TITLE" %}</title>
    {% include "basehead.html" %}
</head>

<body>
    <nav class="navbar is-primary is-spaced">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <img src="{% static 'img/logo/logo.png' %}" alt="谜之屋logo">
            </a>
            <div class="navbar-burger burger" data-target="navMenuColorprimary-example">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuColorprimary-example" class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" href="{% url 'index' %}">首页</a>
                <a class="navbar-item" href="{% url 'sspanel:sshelp' %}">使用说明</a>
                <a class="navbar-item" href="{% url 'sspanel:ssinvite' %}">邀请码</a>
                <a class="navbar-item" href="{% url 'sspanel:ssclient' %}">客户端</a>
                <div class="navbar-item has-dropdown is-hoverable is-hidden-mobile">
                    <span class="navbar-item">
                        <a class="button is-primary is-inverted" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-user-circle"></i>
                            </span>
                            <span>{{ user.username }}</span>
                        </a>
                    </span>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-users"></i>
                            </span>
                            <span>用户中心</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'sspanel:logout' %}">
                            <span class="icon">
                                <i class="fa fa-sign-out"></i>
                            </span>
                            <span>注销登录</span>
                        </a>
                    </div>
                </div>
                <!-- 手机界面菜单-->
                <div class="is-hidden-tablet">
                    <a class="navbar-item is-active">面板管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_index' %}">系统状态</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_invite' %}">邀请相关</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_anno' %}">公告管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_ticket' %}">工单管理</a>
                    <a class="navbar-item is-active">节点管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_node_info' %}">节点列表</a>
                    <a class="navbar-item" href="{% url 'sspanel:alive_user' %}">在线IP</a>
                    <a class="navbar-item is-active">交易管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_charge' %}">充值管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_shop' %}">商品管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:purchase_history' %}">购买记录</a>
                    <a class="navbar-item is-active">用户管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:user_list' %}">用户列表</a>
                    <a class="navbar-item" href="{% url 'sspanel:user_status' %}">用户分析</a>
                    <a class="navbar-item is-active">面板跳转</a>
                    <a class="navbar-item" href="/admin">数据后台</a>
                    <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">用户面板</a>
                </div>
            </div>
        </div>
    </nav>
    <section class="hero is-small is-primary">
        <!-- Hero content: will be in the middle -->
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">
                    <a href="/">
                        <strong>{% settings_value "SUBTITLE" %}</strong>
                    </a>
                </h1>
                <h2 class="subtitle">
                    你说会发现什么呢？
                </h2>
            </div>
        </div>
    </section>
    <br/>
    <div class="container is-fluid">
        <div class="columns">
            <div class="column is-2 is-hidden-mobile">
                <div class="box">
                    {% if user.is_authenticated %}
                    <aside class="menu">
                        <p class="menu-label">
                            面板管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:backend_index' %}">系统状态</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:backend_invite' %}">邀请相关</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:backend_anno' %}">公告管理</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:backend_ticket' %}">工单管理</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            节点管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:backend_node_info' %}">节点列表</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:alive_user' %}">在线IP</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            交易管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:backend_charge' %}">充值管理</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:backend_shop' %}">商品管理</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:purchase_history' %}">购买记录</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            用户管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:user_list' %}">用户列表</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:user_status' %}">用户分析</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            面板跳转
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="/admin">数据后台</a>
                            </li>
                        </ul>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:userinfo' %}">用户面板</a>
                            </li>
                        </ul>
                        {% endif %}
                    </aside>
                </div>
            </div>
            <div class="column is-10">
                {% block main %} {% endblock main%}
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    <p class="copyright">&copy; 2018·
                        <a href="https://github.com/ehco1996">GitHub</a>
                    </p>
                </p>
            </div>
        </div>
    </footer>
</body>
<!--整站消息提醒功能 -->
{% if messages %}
<script>
    {% for message in messages %}
    swal("{{ message.extra_tags }}", '{{ message }}', '{{ message.level_tag }}');
    {% endfor %}
</script>
{% endif %}
</html>

templates/base.html
{% load ehcofilter %}
<!DOCTYPE html>
<html lang="zh">

<head>
    {% load staticfiles %}
    <title>{% settings_value "TITLE" %}</title>
    {% include "basehead.html" %}
</head>

<body>
    <nav class="navbar is-info is-spaced">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'index' %}">
                <img src="{% static 'img/logo/logo.png' %}" alt="谜之屋logo" width="112" height="28">
            </a>
            <div class="navbar-burger burger" data-target="navMenuColorprimary-example">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuColorprimary-example" class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" href="{% url 'index' %}">首页</a>
                <a class="navbar-item" href="{% url 'sspanel:sshelp' %}">使用说明</a>
                <a class="navbar-item" href="{% url 'sspanel:ssinvite' %}">邀请码</a>
                {% if user.is_authenticated %}
                <a class="navbar-item" href="{% url 'sspanel:ssclient' %}">客户端</a>
                <div class="navbar-item has-dropdown is-hoverable is-hidden-mobile">
                    <span class="navbar-item">
                        <a class="button is-info is-inverted" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-user-circle"></i>
                            </span>
                            <span>{{ user.username }}</span>
                        </a>
                    </span>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-users"></i>
                            </span>
                            <span>用户中心</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'sspanel:logout' %}">
                            <span class="icon">
                                <i class="fa fa-sign-out"></i>
                            </span>
                            <span>注销登录</span>
                        </a>
                    </div>
                </div>
                <!-- 手机界面菜单-->
                <div class="is-hidden-tablet">
                    <a class="navbar-item is-active">我的信息</a>
                    <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">账户信息</a>
                    <a class="navbar-item" href="{% url 'sspanel:announcement' %}">查看公告</a>
                    <a class="navbar-item" href="{% url 'sspanel:ticket' %}">联系站长</a>
                    <a class="navbar-item is-active">节点相关</a>
                    <a class="navbar-item" href="{% url 'sspanel:nodeinfo' %}">节点信息</a>
                    <a class="navbar-item" href="{% url 'sspanel:userinfo_edit' %}">节点编辑</a>
                    <a class="navbar-item" href="{% url 'sspanel:trafficlog' %}">流量记录</a>
                    <a class="navbar-item is-active">交易相关</a>
                    <a class="navbar-item" href="{% url 'sspanel:donate' %}">捐赠充值</a>
                    <a class="navbar-item" href="{% url 'sspanel:chargecenter' %}">充值界面</a>
                    <a class="navbar-item" href="{% url 'sspanel:shop' %}">商品界面</a>
                    <a class="navbar-item" href="{% url 'sspanel:purchaselog' %}">购买记录</a>
                    <a class="navbar-item is-active">邀请相关</a>
                    <a class="navbar-item" href="{% url 'sspanel:affiliate' %}">邀请管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:rebate' %}">返利记录</a>
                    {% if perms.sspanel %}
                    <a class="navbar-item is-active">管理面板</a>
                    <a class="navbar-item" href="/admin">数据后台</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_index' %}">网站后台</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
    <section class="hero is-small is-info">
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">
                    <a href="/">
                        <strong>{% settings_value "SUBTITLE" %}</strong>
                    </a>
                </h1>
                <h2 class="subtitle">
                    你说会发现什么呢？
                </h2>
            </div>
        </div>
    </section>
    <hr>
    <main class="bd-main">
        <div class="container is-fluid">
            <div class="columns">
                <div class="column is-2 is-hidden-mobile">
                    <div class="box">
                        {% if user.is_authenticated %}
                        <aside class="menu">
                            <p class="menu-label">
                                我的信息：
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a class="" href="{% url 'sspanel:userinfo' %}">账户信息</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:announcement' %}">查看公告</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:ticket' %}">联系站长</a>
                                </li>
                            </ul>
                            <p class="menu-label">
                                节点相关
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a href="{% url 'sspanel:nodeinfo' %}">节点信息</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:userinfo_edit' %}">节点编辑</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:trafficlog' %}">流量记录</a>
                                </li>
                            </ul>
                            <p class="menu-label">
                                交易相关
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a href="{% url 'sspanel:donate' %}">捐赠付费</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:chargecenter' %}">充值界面</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:shop' %}">商品界面</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:purchaselog' %}">购买记录</a>
                                </li>
                            </ul>
                            <p class="menu-label">
                                邀请相关
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a href="{% url 'sspanel:affiliate' %}">邀请管理</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:rebate' %}">返利记录</a>
                                </li>
                            </ul>
                            {% if perms.sspanel %}
                            <p class="menu-label">
                                管理面板
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a href="/admin">数据后台</a>
                                </li>
                            </ul>
                            <ul class="menu-list">
                                <li>
                                    <a href="{% url 'sspanel:backend_index' %}">网站后台</a>
                                </li>
                            </ul>
                            {% endif %} {% else %}
                            <article class="message is-primary">
                                <div class="message-header">
                                    <p>幻想乡：</p>
                                    <button class="delete"></button>
                                </div>
                                <div class="message-body">
                                    幻想中的:「地方」
                                </div>
                            </article>
                            <article class="message is-info">
                                <div class="message-header">
                                    <p>谜の屋：</p>
                                    <button class="delete"></button>
                                </div>
                                <div class="message-body">
                                    他不存于:「地表」
                                </div>
                            </article>
                            <article class="message is-success">
                                <div class="message-header">
                                    <p>时之塔：</p>
                                    <button class="delete"></button>
                                </div>
                                <div class="message-body">
                                    这囚禁着：「思想」
                                </div>
                            </article>
                            <article class="message is-warning">
                                <div class="message-header">
                                    <p>旧の桥</p>
                                    <button class="delete"></button>
                                </div>
                                <div class="message-body">
                                    却连接着：「自由」
                                </div>
                            </article>
                            {% endif %}
                        </aside>
                    </div>
                </div>

                <div class="column is-10">

                    {% block main %} {% endblock main%}

                </div>
            </div>
        </div>
    </main>
    <footer>
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    <p class="copyright">&copy; 2018·
                        <a href="https://github.com/ehco1996">GitHub</a>
                    </p>
                </p>
            </div>
        </div>
    </footer>
</body>
<!--整站消息提醒功能 -->
{% if messages %}
<script>
    {% for message in messages %}
    swal("{{ message.extra_tags }}", '{{ message }}', '{{ message.level_tag }}');
    {% endfor %}
</script>
{% endif %}

</html>

templates/basehead.html
{% load staticfiles %}
<!-- meta -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="{% static 'img/logo/logo.ico' %}" />

<!-- css -->
{% if user.theme %}
<link href="https://cdn.bootcss.com/bulmaswatch/0.6.2/{{ user.theme }}/bulmaswatch.min.css" rel="stylesheet">
    {% if user.theme == "default" %}
    <link rel="stylesheet" href="https://cdn.bootcss.com/bulma/0.7.1/css/bulma.css" rel="stylesheet">
    {% endif %}
{% else %}
<link rel="stylesheet" href="https://cdn.bootcss.com/bulma/0.7.1/css/bulma.css" rel="stylesheet">
{% endif %}

<link rel="stylesheet" href="{% static 'sspanel/css/ehco.css'%}">
<link rel="stylesheet" href="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.css" integrity="sha256-9MbYWPlETRYDxprjQWUUAkiU6JtQaY1EustxQWdQwhk=" crossorigin="anonymous" />

<link rel="stylesheet" href="https://cdn.bootcss.com/simplemde/1.11.2/simplemde.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<!-- js -->
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.js"></script>
<script src="https://cdn.bootcss.com/simplemde/1.11.2/simplemde.min.js"></script>
<script src="https://cdn.bootcss.com/Chart.js/2.7.1/Chart.bundle.min.js"></script>
<script src="https://cdn.bootcss.com/clipboard.js/1.7.1/clipboard.min.js"></script>
<script src="{% static 'sspanel/js/ehcov1.js' %}"></script>