apps/api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path('user/data/', views.userData, name='userdata'),
    path('node/data/', views.nodeData, name='nodedata'),
    path('donate/data/', views.donateData, name='donatedata'),
    path('random/port/', views.change_ss_port, name='changessport'),
    path('gen/invitecode/', views.gen_invite_code, name='geninvitecode'),
    path('shop/', views.purchase, name='purchase'),
    path('pay/request/', views.pay_request, name='pay_request'),
    path('pay/query/', views.pay_query, name='pay_query'),
    path('traffic/query/', views.traffic_query, name='traffic_query'),
    path('change/theme/', views.change_theme, name='change_theme'),
    path('checkin/', views.checkin, name='checkin'),
    # 邀请码接口
    path('get/invitecode/', views.get_invitecode),
    # web api 接口
    path('nodes/<int:node_id>', views.node_api),
    path('nodes/online', views.node_online_api),
    path('users/nodes/<int:node_id>', views.user_api),
    path('traffic/upload', views.traffic_api),
    path('nodes/aliveip', views.alive_ip_api),
]

apps/sspanel/urls.py
from django.urls import path
from .import views


app_name = "sspanel"
urlpatterns = [
    # 网站用户面板
    path('sshelp/', views.sshelp, name='sshelp'),
    path('ssclient/', views.ssclient, name='ssclient'),
    path('ssinvite/', views.ssinvite, name='ssinvite'),
    path('passinvite/(<invitecode>)/',
         views.pass_invitecode, name='passinvitecode'),
    # 注册/登录
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    # 节点
    path('nodeinfo/', views.nodeinfo, name='nodeinfo'),
    path('trafficlog/', views.trafficlog, name='trafficlog'),
    # 用户信息
    path('users/userinfo/', views.userinfo, name='userinfo'),
    path('users/userinfoedit/', views.userinfo_edit, name='userinfo_edit'),
    #  二维码
    path('qrcode/ssr/<node_id>/',
         views.get_ssr_qrcode, name='ssrqrcode'),
    path('qrcode/ss/<node_id>/',
         views.get_ss_qrcode, name='ssqrcode'),
    # 捐赠/充值
    path('donate/', views.donate, name='donate'),
    path('shop/', views.shop, name='shop'),
    path('purchaselog/', views.purchaselog, name='purchaselog'),
    path('chargecenter/', views.chargecenter, name='chargecenter'),
    path('charge/', views.charge, name='charge'),
    # 公告
    path('announcement/', views.announcement, name='announcement'),
    # 工单
    path('ticket/', views.ticket, name='ticket'),
    path('ticket/create/', views.ticket_create, name='ticket_create'),
    path('ticket/edit/(<int:pk>)/',
         views.ticket_edit, name='ticket_edit'),
    path('ticket/delete/<int:pk>)/',
         views.ticket_delete, name='ticket_delete'),
    # 推广相关
    path('affiliate/', views.affiliate, name='affiliate'),
    path('rebate/record/', views.rebate_record, name='rebate'),
    # 网站后台面板
    path('backend/', views.backend_index, name='backend_index'),
    # 邀请码相关
    path('backend/invite/', views.backend_invite, name='backend_invite'),
    path('invite_gen_code/', views.gen_invite_code, name='geninvitecode'),
    # 节点相关
    path('backend/nodeinfo/', views.backend_node_info,
         name='backend_node_info'),
    path('backend/node/delete/<int:node_id>/',
         views.node_delete, name='node_delete'),
    path('backend/node/edit/<int:node_id>/',
         views.node_edit, name='node_edit'),
    path('backend/node/create/', views.node_create, name='node_create'),
    # 用户相关
    path('backend/userlist/', views.backend_userlist, name='user_list'),
    path('backend/user/delete/<int:pk>/',
         views.user_delete, name='user_delete'),
    path('backend/user/search/', views.user_search, name='user_search'),
    path('backend/user/status/', views.user_status, name='user_status'),
    # 商品充值相关
    path('backend/charge/', views.backend_charge, name='backend_charge'),
    path('backend/shop/', views.backend_shop, name='backend_shop'),
    path('backend/shop/delete/<int:pk>/',
         views.good_delete, name='good_delete'),
    path('backend/good/create/', views.good_create, name='good_create'),
    path('backend/good/edit/<int:pk>/',
         views.good_edit, name='good_edit'),
    path('backend/purchase/history/',
         views.purchase_history, name='purchase_history'),
    # 支付宝当面付相关:
    path('facepay/qrcode/', views.gen_face_pay_qrcode, name='facepay_qrcode'),
    # 公告管理相关
    path('backend/anno/', views.backend_anno, name='backend_anno'),
    path('backend/anno/delete/<int:pk>/',
         views.anno_delete, name='anno_delete'),
    path('backend/anno/create/', views.anno_create, name='anno_create'),
    path('backend/anno/edit/<int:pk>/',
         views.anno_edit, name='anno_edit'),
    # 工单相关
    path('backend/ticket/', views.backend_ticket, name='backend_ticket'),
    path('backend/ticket/edit/<int:pk>/',
         views.backend_ticketedit, name='backend_ticketedit'),
    # 在线ip
    path('backend/aliveuser/', views.backend_alive_user, name='alive_user'),

]

apps/ssserver/urls.py
from django.urls import path
from .import views


app_name = "ssserver"
urlpatterns = [
    path('user/edit/<int:user_id>/', views.user_edit, name='user_edit'),
    path('changesspass/', views.change_ss_pass, name='changesspass'),
    path('changessmethod/', views.change_ss_method, name='changessmethod'),
    path('changessprotocol/', views.change_ss_protocol, name='changessprotocol'),
    path('changessobfs/', views.change_ss_obfs, name='changessobfs'),
    path('subscribe/<token>/', views.subscribe, name='subscribe'),
    path('node/config/', views.node_config, name='node_config'),
]

apps/urls.py
from django.urls import path, include
from django.contrib import admin

from apps.sspanel.views import index

urlpatterns = [
    path('', index, name="index"),
    path('', include('django.contrib.auth.urls')),
    path('api/', include('apps.api.urls', namespace='api')),
    path('sspanel/', include('apps.sspanel.urls', namespace='sspanel')),
    path('server/', include('apps.ssserver.urls', namespace='ssserver')),

    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', 'jet'))
]

apps/sspanel/models.py
import time
import base64
import datetime

import pendulum
import markdown
from decimal import Decimal
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.db import transaction
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator

from apps.payments import alipay
from apps.constants import THEME_CHOICES
from apps.utils import get_long_random_string, traffic_format


class User(AbstractUser):
    '''SS账户模型'''

    invitecode = models.CharField(verbose_name='邀请码', max_length=40)
    invited_by = models.PositiveIntegerField(verbose_name='邀请人id', default=1)
    balance = models.DecimalField(verbose_name='余额', decimal_places=2,
                                  max_digits=10, default=0, editable=True,
                                  null=True, blank=True,)
    invitecode_num = models.PositiveIntegerField(
        verbose_name='可生成的邀请码数量', default=settings.INVITE_NUM)
    level = models.PositiveIntegerField(verbose_name='用户等级', default=0,
                                        validators=[MaxValueValidator(9),
                                                    MinValueValidator(0), ])
    level_expire_time = models.DateTimeField(verbose_name='等级有效期',
                                             default=timezone.now)
    theme = models.CharField(verbose_name='主题', choices=THEME_CHOICES,
                             default=settings.DEFAULT_THEME, max_length=10)

    class Meta(AbstractUser.Meta):
        verbose_name = '用户'

    def delete(self):
        self.ss_user.delete()
        return super(User, self).delete()

    def __str__(self):
        return self.username

    @property
    def expire_time(self):
        '''返回等级到期时间'''
        return self.level_expire_time

    @property
    def sub_link(self):
        '''生成该用户的订阅地址'''
        token = base64.b64encode(bytes(self.username, 'utf-8')).decode('ascii')
        sub_link = settings.HOST + 'server/subscribe/' + token + '/'
        return sub_link

    @property
    def ss_user(self):
        from apps.ssserver.models import Suser
        return Suser.objects.get(user_id=self.id)

    @classmethod
    def get_user_num(cls):
        '''返回用户总数'''
        return cls.objects.all().count()

    @classmethod
    def get_today_register_user(cls):
        '''返回今日注册的用户'''
        today = datetime.datetime.combine(datetime.date.today(),
                                          datetime.time.min)
        return cls.objects.filter(date_joined__gt=today)

    @classmethod
    def add_new_user(cls, cleaned_data):
        from apps.ssserver.models import Suser
        with transaction.atomic():
            username = cleaned_data['username']
            email = cleaned_data['email']
            password = cleaned_data['password1']
            invitecode = cleaned_data['invitecode']
            user = cls.objects.create_user(username, email, password)
            code = InviteCode.objects.get(code=invitecode)
            code.isused = True
            code.save()
            # 将user和ssuser关联
            Suser.objects.create(user_id=user.id, port=Suser.get_random_port())
            # 绑定邀请人
            user.invited_by = code.code_id
            user.invitecode = invitecode
            user.save()
            return user


class InviteCode(models.Model):
    '''邀请码'''

    INVITE_CODE_TYPE = ((1, '公开'), (0, '不公开'))

    code_type = models.IntegerField(
        verbose_name='类型', choices=INVITE_CODE_TYPE, default=0,)
    code_id = models.PositiveIntegerField(verbose_name='邀请人ID', default=1)
    code = models.CharField(verbose_name='邀请码', primary_key=True, blank=True,
                            max_length=40, default=get_long_random_string)
    time_created = models.DateTimeField(
        verbose_name='创建时间', editable=False, auto_now_add=True)
    isused = models.BooleanField(verbose_name='是否使用', default=False,)

    def __str__(self):
        return str(self.code)

    class Meta:
        verbose_name_plural = '邀请码'
        ordering = (
            'isused',
            '-time_created',
        )


class RebateRecord(models.Model):
    '''返利记录'''

    user_id = models.PositiveIntegerField(verbose_name='返利人ID', default=1)
    rebatetime = models.DateTimeField(
        verbose_name='返利时间', editable=False, auto_now_add=True)
    money = models.DecimalField(
        verbose_name='金额', decimal_places=2, null=True, default=0, max_digits=10, blank=True)

    class Meta:
        ordering = ('-rebatetime', )


class Donate(models.Model):
    @classmethod
    def totalDonateMoney(cls):
        '''返回捐赠总金额'''
        return sum([d.money for d in cls.objects.all()])

    @classmethod
    def totalDonateNums(cls):
        '''返回捐赠总数量'''
        return len(cls.objects.all())

    @classmethod
    def richPeople(cls):
        '''返回捐赠金额最多的前10名'''
        rec = {}
        for d in cls.objects.all():
            if d.user not in rec.keys():
                rec[d.user] = d.money
            else:
                rec[d.user] += d.money
        return sorted(rec.items(), key=lambda rec: rec[1], reverse=True)[:10]

    '''捐赠记录'''
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='捐赠人')
    time = models.DateTimeField('捐赠时间', editable=False, auto_now_add=True)
    money = models.DecimalField(
        verbose_name='捐赠金额', decimal_places=2, max_digits=10, default=0, null=True, blank=True)

    def __str__(self):
        return '{}-{}'.format(self.user, self.money)

    class Meta:
        verbose_name_plural = '捐赠记录'
        ordering = ('-time', )


class MoneyCode(models.Model):
    '''充值码'''
    user = models.CharField(
        verbose_name='用户名', max_length=128, blank=True, null=True)
    time = models.DateTimeField('捐赠时间', editable=False, auto_now_add=True)
    code = models.CharField(verbose_name='充值码', unique=True,
                            blank=True, max_length=40, default=get_long_random_string)
    number = models.DecimalField(
        verbose_name='捐赠金额', decimal_places=2, max_digits=10, default=10, null=True, blank=True)
    isused = models.BooleanField(verbose_name='是否使用', default=False)

    def clean(self):
        # 保证充值码不会重复
        code_length = len(self.code or '')
        if 0 < code_length < 12:
            self.code = '{}{}'.format(self.code, get_long_random_string())
        else:
            self.code = get_long_random_string()

    def __str__(self):
        return self.code

    class Meta:
        verbose_name_plural = '充值码'
        ordering = ('isused', )


class Goods(models.Model):
    '''商品'''

    STATUS_TYPE = (
        (1, '上架'),
        (-1, '下架'),
    )

    name = models.CharField(verbose_name='商品名字', max_length=128, default='待编辑')
    content = models.CharField(
        verbose_name='商品描述', max_length=256, default='待编辑')
    transfer = models.BigIntegerField(
        verbose_name='增加的流量', default=settings.GB)
    money = models.DecimalField(
        verbose_name='金额', decimal_places=2, max_digits=10, default=0, null=True, blank=True)
    level = models.PositiveIntegerField(verbose_name='设置等级', default=0, validators=[
                                        MaxValueValidator(9), MinValueValidator(0), ])
    days = models.PositiveIntegerField(verbose_name='设置等级时间(天)', default=1, validators=[
        MaxValueValidator(365), MinValueValidator(1)])
    status = models.SmallIntegerField('商品状态', default=1, choices=STATUS_TYPE)
    order = models.PositiveSmallIntegerField('排序', default=1)

    def __str__(self):
        return self.name

    @property
    def total_transfer(self):
        '''增加的流量'''
        return traffic_format(self.transfer)

    def get_days(self):
        '''返回增加的天数'''
        return '{}'.format(self.days)

    class Meta:
        verbose_name_plural = '商品'
        ordering = [
            'order',
        ]


class PurchaseHistory(models.Model):
    '''购买记录'''

    good = models.ForeignKey(
        Goods, on_delete=models.CASCADE, verbose_name='商品名')
    user = models.CharField(verbose_name='购买者', max_length=128)
    money = models.DecimalField(
        verbose_name='金额', decimal_places=2, max_digits=10, default=0, null=True, blank=True)
    purchtime = models.DateTimeField('购买时间', editable=False, auto_now_add=True)

    def __str__(self):
        return self.user

    class Meta:
        verbose_name_plural = '购买记录'
        ordering = ('-purchtime', )

    @classmethod
    def cost_statistics(cls, good_id, start, end):
        start = pendulum.parse(start, tz=timezone.get_current_timezone())
        end = pendulum.parse(end, tz=timezone.get_current_timezone())
        query = cls.objects.filter(
            good__id=good_id, purchtime__gte=start, purchtime__lte=end)
        for obj in query:
            print(obj.user, obj.good)
        count = query.count()
        amount = count * obj.money
        print('{} ~ {} 时间内 商品: {} 共销售 {} 次 总金额 {} 元'.format(
            start.date(), end.date(), obj.good, count, amount))


class PayRecord(models.Model):
    '''充值流水单号记录'''

    username = models.CharField(
        verbose_name='用户名', max_length=64, blank=False, null=False)
    info_code = models.CharField(
        verbose_name='流水号', max_length=64, unique=True)
    time = models.DateTimeField(verbose_name='时间', auto_now_add=True)
    amount = models.DecimalField(
        verbose_name='金额', decimal_places=2, max_digits=10, default=0, null=True, blank=True)
    money_code = models.CharField(
        verbose_name='充值码', max_length=64, unique=True)
    charge_type = models.CharField(verbose_name='充值类型', max_length=10,
                                   default=1,
                                   help_text='1：支付宝 2：QQ钱包 3：微信支付')

    def __str__(self):
        return self.info_code

    class Meta:
        verbose_name_plural = '支付转账记录'
        ordering = ('-time', )


class PayRequest(models.Model):
    '''支付申请记录'''

    username = models.CharField(

templates/sspanel/index.html
{% extends 'base.html' %} {% block main %}
<div class="columns">
    <div class="column is-one-third">
        <div class="notification is-danger">
            <button class="delete"></button>
            <p class="title is-4">
                好像发现了一个
                <br/>
                <br/>了不得的地方！
            </p>
        </div>
    </div>
    <div class="column is-one-third">
        <div class="notification is-success">
            <button class="delete"></button>
            <p class="title is-4">
                是啊是啊！
                <br/>
                <br/>要进去瞧瞧么？</p>
        </div>
    </div>
    <div class="column is-one-third">
        <div class="notification is-link">
            <button class="delete"></button>
            <p class="title is-4">
                当然要去！
                <br/>
                <br/>魔王总要救公主！</p>
        </div>
    </div>
</div>
<br/> {% if user.is_authenticated %}
<div class="box">
    <p class="title">欢迎小主: {{ user.username }}</p>
    <p class="subtitle">点击下方按钮进入用户中心 </p>
    <button class="button">
        <a href="{% url 'sspanel:userinfo' %}">进入</a>
    </button>

</div>
{% else %}
<div class="column box ">
    {% if allow_register is True %}
    <h1 class="title"> 注册注册</h1>
    <h2 class="subtitle">没有账号？快去注册一个吧！</h2>
    <a class="button is-primary is-outlined" href="{% url 'sspanel:register' %}">注册</a>
    {% else %}
    <h1 class="title"> 抱歉抱歉！</h1>
    <h2 class="subtitle">暂时关闭注册了呢~</h2>
    {% endif %}
</div>
<br/>
<div class="column box ">
    <h1 class="title"> 登录登录！</h1>
    <h2 class="subtitle">有账号了？登录吧少年！</h2>
    <a class="button is-danger is-outlined" href="{% url 'sspanel:login' %}">登录</a>
</div>
<br/> {% endif %} {% endblock main %}

templates/sspanel/ticket.html
{% extends 'base.html' %} {% block main %}

<div class="column is-12">
    <section class="hero is-success">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    工单系统：
                </h1>
                <h2 class="subtitle">
                    有什么问题尽管提！什么时候解决就不知道了！
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">
    <div class="box">
        <div class="content">
            <p class="subtitle">我的工单:</p>
            <table class="table is-striped">
                <thead>
                    <tr>
                        <th>操作:</th>
                        <th>ID:</th>
                        <th>时间:</th>
                        <th>标题:</th>
                        <th>状态</th>
                    </tr>
                </thead>

                {% for record in ticket %}
                <tr>
                    <td><a class="button is-info" href="{% url 'sspanel:ticket_edit' record.pk %}">查看</a><br>
                        <a class="button is-danger" href="{% url 'sspanel:ticket_delete' record.pk %}">删除</a></td>                
                    <td>#{{ record.pk }}</td>
                    <td>{{ record.time }}</td>
                    <td>{{ record.title }}</td>
                    <td>{{ record.get_status_display }}</td>
                </tr>
                {% empty %}
                <h2 class="subtitle">
                    暂时还没提过工单呢
                </h2>
                {% endfor %}
            </table>
            <p align="right"><a class="button is-danger is-outlined" href="{% url 'sspanel:ticket_create' %}">发起工单</a></p>
        </div>
    </div>
</div>





{% endblock main %}

templates/sspanel/userinfo.html
{% extends 'base.html' %} {% block main %}
<div class="column is-12">
    <section class="hero is-primary is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    用户中心：
                </h1>
                <h2 class="subtitle">
                    这里有你的出生证明....
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="tile is-ancestor">

        <div class="tile is-5 is-vertical is-parent">
            <div class="tile box is-child">
                <p class="title">
                    <span class="icon is-large">
                        <i class="fa fa-home"></i>
                    </span> 欢迎小主: {{ user.username }}</p>
                <p class="subtitle is-5">这里的功能还比较少...</p>
                <button class="button is-rounded">
                    <a href="{% url 'sspanel:logout' %}">注销登录</a>
                </button>
                <button class="button is-rounded">
                    <a href="{% url 'password_change' %}">修改密码</a>
                </button>
                <button class="button is-rounded">
                    <a>
                        <span id="id-change-port">重置端口</span>
                    </a>
                </button>
                <hr>
                <div class="field is-grouped">
                    <div class="control has-icons-left">
                        <div class="select is-rounded is-fullwidth">
                            <select name="selects">
                                <option value="" disabled="" selected="">更换页面主题</option>
                                <option disabled="">───</option>
                                {% for theme in  themes %}
                                <option value="{{ theme.0 }}">{{ theme.1 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="icon is-small is-left">
                            <i class="fa fa-eercast"></i>
                        </div>
                    </div>
                    <p class="control">
                        <button class="button is-outlined is-info is-rounded" id="id-button-theme">提交</button>
                    </p>
                </div>
                <hr>
                <div id="id-checkin-box">
                    {% if user.ss_user.today_is_checked %}
                    <p class="subtitle is-5 is-spaced">今天已经签到过了ಠ౪ಠ</p>
                    {% else %}
                    <p class="subtitle is-5 is-spaced"> 今天还没有签到，点一下可以获得{{ min_traffic }}~{{ max_traffic }}流量</p>
                    <br>
                    <button class="button">
                        <a>
                            <span id="id-checkin">签到</span>
                        </a>
                    </button>
                    {% endif %}
                </div>
            </div>
            <div class="tile box is-child">
                <article class="message">
                    <div class="message-header">
                        <p>最新公告</p>
                    </div>
                    <div class="message-body">
                        {% if anno %} {{ anno.body | safe }} {% else %}
                        <p>暂无公告</p>
                        {% endif %}
                    </div>
                </article>
            </div>
        </div>

        <div class="tile is-7 is-vertical is-parent">

            <div class="tile box is-child">
                <article class="message is-success">
                    <div class="message-header">
                        <p>连接信息</p>
                    </div>
                    <div class="message-body">
                        <li> 端口：
                            <code><span id="port">{{ user.ss_user.port }}</span></code>
                        </li>
                        <li> 密码：
                            <code>{{ user.ss_user.password }}</code>
                        </li>
                        <li> 加密：
                            <code>{{ user.ss_user.method }}</code>
                        </li>
                        <li> 协议：
                            <code>{{ user.ss_user.protocol }}</code>
                        </li>
                        <li> 混淆：
                            <code>{{ user.ss_user.obfs }}</code>
                        </li>
                        <br>
                        <div class="buttons">
                            <a class="button is-link is-rounded" href="{{ sub_code }}">一键导入</a>
                            <a class="button is-link is-rounded" href="{% url 'ssserver:node_config' %}" download>配置下载</a>
                            <span class="button is-link modal-button is-rounded" data-target="modal-sub">订阅</span>
                        </div>
                    </div>
                </article>
                <div class="modal nodeinfo" id="modal-sub">
                    <div class="modal-background"></div>
                    <div class="modal-card">
                        <header class="modal-card-head">
                            <p class="modal-card-title">SSR订阅地址：</p>
                            <button class="delete"></button>
                        </header>
                        <section class="modal-card-body">
                            <p class="subtitle">订阅链接</p>
                            <strong>点击按钮复制链接至客户端的订阅处</strong>
                            <div class="field is-grouped">
                                <p class="control is-expanded">
                                    <input class="input" id="id-sub-link" value="{{ sub_link }}">
                                </p>
                                <p class="control">
                                    <a class="button is-rounded" id="id-button-clip" data-clipboard-target="#id-sub-link">
                                        <i class="fa fa-clipboard" aria-hidden="true"></i>
                                    </a>
                                </p>
                            </div>
                            <span class="copied" hidden="true">Copied!</span>
                        </section>
                    </div>
                </div>
                <article class="message is-warning">
                    <div class="message-header">
                        <p>流量信息</p>
                    </div>

                    <div class="message-body">
                        <div class="columns">
                            <div class="column is-4">
                                <li>总量:
                                    <code>{{ user.ss_user.totla_transfer }}</code>
                                </li>
                            </div>
                            <div class="column">
                                <progress class="progress is-success" value="100" max="100"></progress>
                            </div>
                        </div>
                        <div class="columns">
                            <div class="column is-4">
                                <li>剩余:
                                    <code>{{ remain_traffic }}% </code>
                                </li>
                            </div>
                            <div class="column">
                                <progress class="progress is-info" value="{{  remain_traffic }}" max="100"></progress>
                            </div>
                        </div>

                        <div class="columns">
                            <div class="column is-4">
                                <li>使用:
                                    <code>{{ user.ss_user.used_traffic }}</code> </li>
                            </div>
                            <div class="column">
                                <progress class="progress is-danger" value="{{  user.ss_user.used_percentage }}" max="100"></progress>
                            </div>
                        </div>
                    </div>
                </article>

                <article class="message is-info">
                    <div class="message-header">
                        <p>个人信息</p>
                    </div>
                    <div class="message-body">
                        <li> 余额：
                            <code>{{ user.balance }} 元</code>
                        </li>
                        <li> 邮箱：
                            <code>{{ user.email }} </code>
                        </li>
                        <li> 等级：
                            <code>{{ user.level }} 级 </code>
                        </li>
                        {% if user.ss_user.enable == True %}
                        <li> 状态：
                            <code>正常使用</code>
                        </li>
                        {% else %}
                        <li> 状态：
                            <code>失效</code>
                        </li>
                        {% endif %}
                        <li> 等级到期时间：
                            <code>{{ user.expire_time }} </code>
                        </li>
                        <li>上次使用时间:
                            <code>{{ user.ss_user.user_last_use_time|date:"m月d日G点" }}</code>
                        </li>

                    </div>
                </article>

            </div>
        </div>
    </div>
</div>

<script>
    // 点击复制
    var clip = new Clipboard('#id-button-clip');
    clip.on('success', function (e) {
        $('.copied').show();
        $('.copied').fadeOut(1000);
    });
    // 端口重置Ajax部分
    var ProtButton = $("#id-change-port")
    var changeport = function () {
        url = "{% url 'api:changessport' %}"
        $.getJSON(url, function (results) {
            swal(results.title, results.subtitle, results.status)
            port.textContent = results.subtitle.slice(6, -1)
        })
    }
    ProtButton.click(changeport)
    // 签到AJAX部分
    var CheckButton = $("#id-checkin")
    var Checkin = function () {
        url = "{% url 'api:checkin' %}"
        $.getJSON(url, function (results) {
            swal(results.title, results.subtitle, results.status)
            var box = $("#id-checkin-box")
            box.html('<p class="subtitle is-5 is-spaced">今天已经签到过了ಠ౪ಠ</p>')
        })
    }
    CheckButton.click(Checkin)
    // 更换主题
    var ThemeButton = $("#id-button-theme")
    var changeTheme = function () {
        var theme = $("select[name=selects]").val();
        if (theme) {
            data = {
                theme: theme,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            }
            url = "{% url 'api:change_theme' %}"
            $.post(url, data, function (results) {
                info = results
                swal(info.title, info.subtitle, info.status)
            })
        } else {
            swal('错误！', '请选择你要更换的主题', 'error')
        }
    }

    ThemeButton.click(changeTheme)
</script> {% endblock main %}